FROM alpine:3.12
# RUN apk update && apk upgrade && apk add bash \
# && apk add php7-common php7-session php7-iconv php7-json php7-gd php7-curl php7-xml php7-mysqli php7-imap php7-cgi fcgi php7-pdo php7-pdo_mysql php7-soap php7-xmlrpc php7-posix php7-mcrypt php7-gettext php7-ldap php7-ctype php7-dom
# RUN wget https://files.phpmyadmin.net/phpMyAdmin/5.1.0/phpMyAdmin-5.1.0-all-languages.tar.gz && tar zxvf phpMyAdmin-5.1.0-all-languages.tar.gz \
# && rm phpMyAdmin-5.1.0-all-languages.tar.gz && mv phpMyAdmin-5.1.0-all-languages/ phpmyadmin

# COPY scriptpma.sh /
# RUN chmod +x scriptpma.sh
# CMD ./scriptpma.sh

EXPOSE 5000